//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreCMS3.Areas.Prod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CastMember
    {
        public int CastMemberId { get; set; }
        public string Name { get; set; }
        public Nullable<int> YearJoined { get; set; }
        public int MainRole { get; set; }
        public string Bio { get; set; }
        public bool CurrentMember { get; set; }
        public string Character { get; set; }
        public Nullable<int> CastYearLeft { get; set; }
        public Nullable<int> DebutYear { get; set; }
        public byte[] Photo { get; set; }
    }
}
