//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreCMS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalRequest
    {
        public int RentalRequestId { get; set; }
        public string ContactPerson { get; set; }
        public string Company { get; set; }
        public System.DateTime RequestedTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string ProjectInfo { get; set; }
        public int RentalCode { get; set; }
        public bool Accepted { get; set; }
        public bool ContractSigned { get; set; }
        public int MyProperty { get; set; }
    }
}
