//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreCMS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalId { get; set; }
        public string RentalName { get; set; }
        public int RentalCost { get; set; }
        public string FlawsAndDamages { get; set; }
        public Nullable<bool> ChokingHazard { get; set; }
        public Nullable<bool> SuffocationHazard { get; set; }
        public Nullable<int> PurchasePrice { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> SquareFootage { get; set; }
        public Nullable<int> MaxOccupancy { get; set; }
        public string Discriminator { get; set; }
    }
}
