// <auto-generated />
namespace TheatreCMS3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class blogphoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blogphoto));
        
        string IMigrationMetadata.Id
        {
            get { return "202111250935531_blogphoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
